# 使用官方的 Nginx 镜像作为运行环境
FROM nginx:alpine

# 复制构建好的文件到 Nginx 默认服务路径
COPY ui/dist /usr/share/nginx/html

# 复制 Nginx 配置文件
COPY ui/kb.conf /etc/nginx/conf.d/kb.conf

# 暴露端口
EXPOSE 80

# 启动 Nginx
CMD ["nginx", "-g", "daemon off;"]
